security:
  photon:
    username: photonprod
    password: cGhvdG9ucHJvZEAxMjM=
  personal:
    username: bharath
    password: YmhhcmF0aEAxMjM=
lms:
  message: "Welcome to Leave Services related PROD APIs "
  contactDetails:
    name: "Bharath - PROD Lead"
    email: "bharath@lms.com"
  onCallSupport:
    - 9948373056
    - 8701472885