security:
  photon:
    username: photon
    password: cGhvdG9uQDEyMw==
  personal:
    username: shekhar
    password: U2hla2hhckAxMjM=
lms:
  message: "Welcome to Leave Services related DEV APIs "
  contactDetails:
    name: "Shekhar - DEV Lead"
    email: "shekharthr@lms.com"
  onCallSupport:
    - 9000626559
    - 7356411673
#logging:
#  file:
#    name: logs/app.log